name: Explain New Solutions

on:
  push:
    paths:
      - 'codechef/**'
      - 'scripts/**'
  schedule:
    - cron: '0 12 * * *'  
  workflow_dispatch:

jobs:
  explain:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate/Update READMEs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/explain.py

      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          pull: true                 
          commit_message: "chore: add/update problem READMEs with explanations"
          branch: ${{ github.ref_name }}
